# ===================================
# Docker Compose para Ambiente Ansible
# Sprint 2: Nodo de Control + Managed Nodes
# ===================================

services:
  # ===================================
  # Ansible Control Node - CentOS Stream 9
  # ===================================
  ansible-control:
    build:
      context: ./ansible-control
      dockerfile: Dockerfile
    container_name: ansible-control
    hostname: ansible-control
    ports:
      - "2200:22"
    networks:
      - ansible-network
    volumes:
      - ansible-data:/ansible
      - ssh-keys:/home/ansible/.ssh
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_SSH_PIPELINING=True
    depends_on:
      - centos9-node-1
      - centos9-node-2
    healthcheck:
      test: ["CMD", "ansible", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # ===================================
  # CentOS 9 - Managed Nodes
  # ===================================
  centos9-node-1:
    build: 
      context: ./centos9
      dockerfile: Dockerfile
    container_name: centos9-node-1
    hostname: centos9-node-1
    ports:
      - "2201:22"  # SSH port mapping
    environment:
      - TZ=America/Mexico_City
      - HOSTNAME=centos9-node-1
    volumes:
      - centos9-node-1-data:/home/ansible
      - centos9-node-1-logs:/var/log/ansible
    networks:
      - ansible-network
    restart: unless-stopped
    privileged: true  # Required for systemd
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /run
      - /tmp
    healthcheck:
      test: ["CMD", "/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  centos9-node-2:
    build: 
      context: ./centos9
      dockerfile: Dockerfile
    container_name: centos9-node-2
    hostname: centos9-node-2
    ports:
      - "2202:22"  # SSH port mapping
    environment:
      - TZ=America/Mexico_City
      - HOSTNAME=centos9-node-2
    volumes:
      - centos9-node-2-data:/home/ansible
      - centos9-node-2-logs:/var/log/ansible
    networks:
      - ansible-network
    restart: unless-stopped
    privileged: true  # Required for systemd
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /run
      - /tmp
    healthcheck:
      test: ["CMD", "/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# ===================================
# Volumes para persistencia de datos
# ===================================
volumes:
  # Volúmenes del nodo de control (v1.3.0)
  ansible-data:
    driver: local
    name: ansible_data
  ssh-keys:
    driver: local
    name: ssh_keys
  
  # Volúmenes de los nodos managed
  centos9-node-1-data:
    driver: local
    name: ansible_centos9_node1_data
  centos9-node-1-logs:
    driver: local
    name: ansible_centos9_node1_logs
  centos9-node-2-data:
    driver: local
    name: ansible_centos9_node2_data
  centos9-node-2-logs:
    driver: local
    name: ansible_centos9_node2_logs

# ===================================
# Red interna para comunicación
# ===================================
networks:
  ansible-network:
    driver: bridge
    name: ansible-network
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
