# ===================================
# Docker Compose para Ambiente Ansible
# Sprint 1: Configuración Base CentOS 9
# ===================================

version: '3.8'

services:
  # ===================================
  # CentOS 9 - Managed Nodes
  # ===================================
  centos9-node1:
    build: 
      context: ./centos9
      dockerfile: Dockerfile
    container_name: centos9-node1
    hostname: centos9-node1
    ports:
      - "2201:22"  # SSH port mapping
    environment:
      - TZ=America/Mexico_City
      - HOSTNAME=centos9-node1
    volumes:
      - centos9-node1-data:/home/ansible
      - centos9-node1-logs:/var/log/ansible
    networks:
      - ansible-network
    restart: unless-stopped
    privileged: false
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  centos9-node2:
    build: 
      context: ./centos9
      dockerfile: Dockerfile
    container_name: centos9-node2
    hostname: centos9-node2
    ports:
      - "2202:22"  # SSH port mapping
    environment:
      - TZ=America/Mexico_City
      - HOSTNAME=centos9-node2
    volumes:
      - centos9-node2-data:/home/ansible
      - centos9-node2-logs:/var/log/ansible
    networks:
      - ansible-network
    restart: unless-stopped
    privileged: false
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# ===================================
# Volumes para persistencia de datos
# ===================================
volumes:
  centos9-node1-data:
    driver: local
    name: ansible_centos9_node1_data
  centos9-node1-logs:
    driver: local
    name: ansible_centos9_node1_logs
  centos9-node2-data:
    driver: local
    name: ansible_centos9_node2_data
  centos9-node2-logs:
    driver: local
    name: ansible_centos9_node2_logs

# ===================================
# Red interna para comunicación
# ===================================
networks:
  ansible-network:
    driver: bridge
    name: ansible-network
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
